apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/dragos1993/ArgoCD-Manifest.git'
    targetRevision: main
    path: apps   # <--- IMPORTANT: points to apps/ which contains all child apps

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: true        # delete old children that are removed from repo
      selfHeal: true     # fix drift automatically

    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
