apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dragos1993/ArgoCD-Manifest.git'
    targetRevision: main
    path: apps
    directory:
      recurse: true          # 👈 THIS is the missing piece

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
