apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipv-ui-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/dragos1993/ArgoCD-src-code.git'
      targetRevision: main
      path: charts/ipv-ui
      helm:
        valueFiles:
          - $values/ipv-ui/dev/values-dev.yaml   # 👈 here too
    - repoURL: 'https://github.com/dragos1993/ArgoCD-Manifest.git'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ipv-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
