apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipv-api-dev
  namespace: argocd
spec:
  project: default
  sources:
    # Source 1: Helm chart repo (backend API)
    - repoURL: 'https://github.com/dragos1993/ArgoCD-src-code.git'
      targetRevision: main
      path: charts/ipv-api
      helm:
        valueFiles:
          - $values/ipv-api/dev/values-dev.yaml   # 👈 IMPORTANT: starts with $values
    # Source 2: values repo
    - repoURL: 'https://github.com/dragos1993/ArgoCD-Manifest.git'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ipv-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
