apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipv-ui-test
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/dragos1993/ArgoCD-src-code.git'
      targetRevision: main
      path: charts/ipv-ui
      helm:
        valueFiles:
          - $values/ipv-ui/test/values-test.yaml

    - repoURL: 'https://github.com/dragos1993/ArgoCD-Manifest.git'
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: ipv-test

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
